apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: orders
  name: orders
spec:
  replicas: 1
  selector:
    service: orders
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orders
    spec:
      containers:
      - env:
        - name: APP_OPTIONS
          value: --port=10002 --db=orders-db.sockstore-prod.svc --zipkin=zipkin.sockstore-prod.svc --server.payment.host=payment.sockstore-prod.svc --server.shipping.host=shipping.sockstore-prod.svc
        - name: JAVA_APP_JAR
          value: orders.jar
        image: ' '
        name: orders
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
        ports:
        - containerPort: 10002
          hostPort: 10002
          protocol: TCP
        livenessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10002
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: localhost
            path: /health
            port: 10002
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tmp
          name: orders-tmpfs0
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: orders-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - orders
      from:
        kind: ImageStreamTag
        name: orders:prod
    type: ImageChange
status: {}
