apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: c3-container-cloud14.bj
      containers:
      - env:
        - name: RABBITMQ_NODE_PORT
          value: "10010"
        image: ' '
        name: rabbitmq
        resources: {}
        ports:
        - containerPort: 10010
          hostPort: 10010
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - rabbitmqctl
              - status
          initialDelaySeconds: 10
          timeoutSeconds: 1
        securityContext: 
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-tmp
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp/rabbitmq
        name: rabbitmq-tmp
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rabbitmq
      from:
        kind: ImageStreamTag
        name: rabbitmq:3
    type: ImageChange
status: {}
