apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "10010"
    port: 5672
    targetPort: 10010
  selector:
    service: rabbitmq
status:
  loadBalancer: {}
