apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    service: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    service: zipkin
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: zipkin
    spec:
      containers:
      - image: ' '
        name: zipkin
        ports:
        - containerPort: 9411
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /tmp
          name: zipkin-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir:
        name: zipkin-tmpfs0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - zipkin
      from:
        kind: ImageStreamTag
        name: zipkin:prod
    type: ImageChange
status: {}
