apiVersion: v1
kind: Template
metadata:
  name: project-request
objects:
- apiVersion: v1
  kind: Project
  metadata:
    name: ${PROJECT_NAME}-test
    annotations:
      openshift.io/node-selector: role=comp
    labels:
      project: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: core-resource-limits
    namespace: ${PROJECT_NAME}-test
  spec:
    limits:
    - type: Pod
      max:
        cpu: 16
        memory: 64Gi
      min:
        cpu: 500m
        memory: 512Mi
      maxLimitRequestRatio:
        cpu: "2"
    - type: Container
      default:
        cpu: 1
        memory: 1Gi
      max:
        cpu: 16
        memory: 64Gi
      min:
        cpu: 500m
        memory: 512Mi
      maxLimitRequestRatio:
        cpu: "2"
    - type: PersistentVolumeClaim
      min: 
        storage: 1Gi 
      max:
        storage: 128Gi 
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}-test
  kind: RoleBinding
  metadata:
    name: system:image-pullers
    namespace: ${PROJECT_NAME}-test
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}-test
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: system:image-builders
    namespace: ${PROJECT_NAME}-test
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}-test:builder
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: system:deployers
    namespace: ${PROJECT_NAME}-test
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}-test:deployer
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: admin
    namespace: ${PROJECT_NAME}-test
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: owner
    namespace: ${PROJECT_NAME}-test
  roleRef:
    name: edit
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}
parameters:
- name: PROJECT_NAME
  description: Name of the project
  required: true
- name: PROJECT_ADMIN_USER
  description: Admin user of the project
  required: true
