apiVersion: "v1"
kind: "Service"
metadata: 
  name: "kube-applier"
  namespace: "applier"
spec: 
  ports: 
    - name: "service"
      port: 80
      targetPort: 2020
  selector: 
    service: "applier"
