{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {
                "name": "applier",
                "namespace": "applier"
            }
        },
        {
            "apiVersion": "v1",
            "kind": "RoleBinding",
            "metadata": {
                "name": "applier",
                "namespace": "applier"
            },
            "roleRef": {
                "name": "admin"
            },
            "subjects": [
                {
                    "kind": "ServiceAccount",
                    "name": "applier"
                }
            ]
        }
    ]
}
